# Generated by Django 4.0 on 2021-12-23 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 13, 53, 4, 955612, tzinfo=utc), verbose_name='date published'),
        ),
    ]
