# Generated by Django 4.0 on 2021-12-24 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0003_alter_posts_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 52, 12, 911982, tzinfo=utc), verbose_name='date published')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 52, 12, 911995, tzinfo=utc), verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 52, 12, 911696, tzinfo=utc), verbose_name='date published'),
        ),
    ]
