# Generated by Django 4.0 on 2021-12-24 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0005_paymenttable_alter_category_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 7, 13, 39, 630514, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 7, 13, 39, 630527, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 7, 13, 39, 629625, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
