# Generated by Django 4.0 on 2022-01-03 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0020_alter_category_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttable',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 52, 6, 810774, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 52, 6, 810787, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 52, 6, 810516, tzinfo=utc), verbose_name='date published'),
        ),
    ]
