# Generated by Django 4.0 on 2022-01-03 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0021_paymenttable_user_id_alter_category_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 53, 38, 277288, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 53, 38, 277302, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='paymenttable',
            name='payment_id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 53, 38, 277013, tzinfo=utc), verbose_name='date published'),
        ),
    ]
